---
- name: Playbooks for Arista pre and post operational tests.
  hosts: new_infra
  connection: network_cli
  gather_facts: false

  tasks:
  - name: Handle the error 
    block:
      - name: run BEFORE tests.
        eos_pyateos:
          before: true
          test: "{{ tests }}"
          group: 
            - mgmt
            - layer2
          hostname: "{{ inventory_hostname }}"
        register: result

      - name: save BEFORE file IDs.
        delegate_to: 127.0.0.1
        set_fact:
          before_ids: "{{ result.before_file_ids }}"

      - name: change mgmt config on switch.
        eos_config:
          lines:
            - no ntp server vrf mgmt 10.75.33.5
            - ntp server vrf mgmt 216.239.35.4
            - no snmp-server host 29.0.5.27 vrf mgmt version 2c fluffytail
            - snmp-server host 8.8.8.8 vrf mgmt version 2c fluffytail

      - name: shutdown interface.
        eos_config:
          lines:
            - shutdown
          parents: interface Ethernet50/1

      - name: edit ACL.
        eos_config:
          lines:
            - no 10
            - 10 remark pyATEOS TEST
          parents: ip access-list standard SNMP

      - name: run AFTER tests.
        eos_pyateos:
          after: true
          test: "{{ tests }}"
          group:
            - mgmt
            - layer2
          hostname: "{{ inventory_hostname }}"
        register: result

      - name: save AFTER file IDs.
        delegate_to: 127.0.0.1
        set_fact:
          after_ids: "{{ result.after_file_ids }}"

  
      - name: run DIFF result.
        eos_pyateos:
          compare: true
          group:
            - mgmt
            - layer2
          test: "{{ tests }}"
          hostname: "{{ inventory_hostname }}"
          filter: true
          files: 
            - "{{ before_ids }}"
            - "{{ after_ids }}"
    
    always:
      - name: find backups and renders files older than 5 minutes.
        find:
          paths: ./tests
          age: 5m
          file_type: file
          recurse: yes
        register: find_result

      - name: delete backups and renders files older than 5 minutes.
        file:
          path:  "{{ item.path }}"
          state: absent
        loop: "{{ find_result.files }}"
  
      - name: restore mgmt config on switch.
        eos_config:
          lines:
            - ntp server vrf mgmt 10.75.33.5
            - no ntp server vrf mgmt 216.239.35.4
            - snmp-server host 29.0.5.27 vrf mgmt version 2c fluffytail
            - no snmp-server host 8.8.8.8 vrf mgmt version 2c fluffytail 

      - name: no shutdown interface.
        eos_config:
          lines:
            - no shutdown
          parents: interface Ethernet50/1

      - name: restore ACL.
        eos_config:
          lines:
            - no 10
            - 10 remark AWS-PROD-IE SLW POLLER
          parents: ip access-list standard SNMP
          
#f20200301