---
- name: create ROUTE-MAP config.
  eos_config:
    lines:
      - match interface Loopback10
      - set ip next-hop 10.76.96.165
    parents: route-map T666-loopback permit 10

- name: create AS-PATH config.
  eos_config:
    lines:
      - ip as-path access-list 666 permit ^$ any

- name: create PREFIX-LIST config.
  eos_config:
    lines:
      - ip prefix-list T666 seq 10 permit 8.8.8.8/32

- name: run BEFORE tests.
  eos_pyateos:
    before: true
    group: 
      - ctrl
    hostname: "{{ inventory_hostname }}"
  register: result

- name: save BEFORE file IDs.
  delegate_to: 127.0.0.1
  set_fact:
    before_ids: "{{ result.before_file_ids }}"

- name: change PREFIX-LIST config.
  eos_config:
    lines:
      - no ip prefix-list T666 seq 10 permit 8.8.8.8/32
      - ip prefix-list T999 seq 10 permit 8.8.4.4/32

- name: change ACL config.
  eos_config:
    lines:
      - no 20
      - 20 permit 10.226.234.0/24
    parents: ip access-list standard SNMP

- name: change ROUTE-MAP config.
  eos_config:
    lines:
      - match interface Loopback10
      - set ip next-hop 10.76.96.165
    parents: route-map T999-loopback permit 10

- name: change ROUTE-MAP config.
  eos_config:
    lines:
      - no route-map T666-loopback permit 10

- name: change AS-PATH config.
  eos_config:
    lines:
      - no ip as-path access-list 666 permit ^$ any
      - ip as-path access-list 999 permit ^$ any

- name: run AFTER tests.
  eos_pyateos:
    after: true
    group: 
      - ctrl
    hostname: "{{ inventory_hostname }}"
  register: result

- name: save AFTER file IDs.
  delegate_to: 127.0.0.1
  set_fact:
    after_ids: "{{ result.after_file_ids }}"

- name: restore ACL config.
  eos_config:
    lines:
      - no 20
      - 20 permit 10.226.234.112/28
    parents: ip access-list standard SNMP

- name: restore ROUTE-MAP, AS-PATH config.
  eos_config:
    lines:
      - no ip as-path access-list 999 permit ^$ any
      - no route-map T999-loopback permit 10

- name: change PREFIX-LIST config.
  eos_config:
    lines:
      - no ip prefix-list T999 seq 10 permit 8.8.4.4/32

- name: run DIFF result.
  eos_pyateos:
    compare: true
    group: 
      - ctrl
    hostname: "{{ inventory_hostname }}"
    filter: true
    files: 
      - "{{ before_ids }}"
      - "{{ after_ids }}"