---
- name: run BEFORE tests.
  eos_pyateos:
    before: true
    test: 
      - mac
    hostname: "{{ inventory_hostname }}"
  register: result

- name: save BEFORE file IDs.
  delegate_to: 127.0.0.1
  set_fact:
    before_ids: "{{ result.before_file_ids }}"

- name: change NTP config.
  eos_command:
    commands:
      - clear mac address-table dynamic

- name: run AFTER tests.
  eos_pyateos:
    after: true
    test: 
      - mac
    hostname: "{{ inventory_hostname }}"
  register: result

- name: save AFTER file IDs.
  delegate_to: 127.0.0.1
  set_fact:
    after_ids: "{{ result.after_file_ids }}"
  
- name: run DIFF result.
  eos_pyateos:
    compare: true
    test:
      - mac
    hostname: "{{ inventory_hostname }}"
    filter: true
    files: 
      - "{{ before_ids }}"
      - "{{ after_ids }}"