---
- name: run BEFORE tests.
  eos_pyateos:
    before: true
    test: 
      - ntp
    hostname: "{{ inventory_hostname }}"
  register: result

- name: save BEFORE file IDs.
  delegate_to: 127.0.0.1
  set_fact:
    before_ids: "{{ result.before_file_ids }}"

- name: change NTP config.
  eos_config:
    lines:
      - no ntp server vrf mgmt 10.75.33.5
      - ntp server vrf mgmt 216.239.35.4

- name: run AFTER tests.
  eos_pyateos:
    after: true
    test: 
      - ntp
    hostname: "{{ inventory_hostname }}"
  register: result

- name: save AFTER file IDs.
  delegate_to: 127.0.0.1
  set_fact:
    after_ids: "{{ result.after_file_ids }}"

- name: restore NTP config.
  eos_config:
    lines:
      - ntp server vrf mgmt 10.75.33.5
      - no ntp server vrf mgmt 216.239.35.4
  
- name: run DIFF result.
  eos_pyateos:
    compare: true
    test:
      - ntp
    hostname: "{{ inventory_hostname }}"
    filter: true
    files: 
      - "{{ before_ids }}"
      - "{{ after_ids }}"